### ISSUE TITLE
#4 Issue

### ISSUE THREAD

**Issue by sqrdw** [syznq/PYTHON#1]
The issue keeps going where it says that _Tkinter appears to be missing_, and I could really use some assistance in resolving this!

**Comment by syznq** [comment]
To install Tkinter you must follow these steps: Open the Command Prompt on Windows by typing "cmd" in the windows search bar. Once it has opened enter the command: "pip install tkinter" And then after this installation process is completed that's when you may now continue using your application with its UI working and functioning!

Repo Owner,
_syznq_

### |  I   s   s   u   e  - R e s o l v e d . |

**Comment by sqrdw** [comment]
Thanks!

**Comment by syznq** [comment]
Anytime.
